version: '3.2'
services:
  db:
    image: postgres:alpine
    volumes:
      - ./opt/postgres-data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=contacts
      - POSTGRES_PASSWORD=contacts
      - POSTGRESQL_DATABASE=contacts
  web:
    build: .
    environment:
      - POSTGRES_USER=contacts
      - POSTGRES_PASSWORD=contacts
      - POSTGRESQL_DATABASE=contacts
      - POSTGRESQL_HOSTNAME=db
      - CONTACTS_PAGE_SIZE=100
      - MIX_ENV=prod
    ports:
      - "4000:4000"
    depends_on:
      - db